config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root to: 'welcome#index'
  resources :items
  resources :merchants
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord


end

app/models/merchant.rb
class Merchant < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of  :password, require: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchants = Merchant.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<h1> Little Shop </h1>
<div class='accessories'>
  <%@items.each do |i| %>
  <section>
    <h2> <%=i.name%> </h2>
    <div class='med-image'><img src="<%=i.image%>" alt="Forest"></div>
  </section>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Littleshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/merchants/index.html.erb
<h1> Merchants</h1>
<div class='accessories'>
  <%@merchants.each do |m| %>
  <section>
    <h2> <%=m.name%> </h2>
  </section>
  <%end%>
</div>

app/views/users/new.html.erb
<h1> Create New User </h1>
<%= form_for @user do |f| %>
  <%= f.label :username%>
  <%= f.text_field :username%>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%=f.submit %>
<%end%>

app/views/users/show.html.erb
<h1> Welcome <%=@user.username%>!!</h1>
<h3> <%= link_to 'Log Out', logout_path %></h3>

app/views/welcome/index.html.erb
<h1> Welcome To LittleShop!! </h1>
<h3> <%= link_to 'Home', root_path %></h3>
<h3> <%= link_to 'Items', items_path %></h3>
<h3> <%= link_to 'Merchants', merchants_path %></h3>
<% if current_user %>
  <h3> <%= link_to 'Log Out', logout_path %></h3>
<%else%>
  <h3> <%= link_to 'Log In', login_path %></h3>
  <h3> <%= link_to 'Register', new_user_path %></h3>
<%end%>